### ISSUE TITLE
Does ChatTTSPlus support training my own  voice?

### ISSUE THREAD

**Issue by johnny8353** [warmshao/ChatTTSPlus#21]
Does ChatTTSPlus support training my own  voice?

**Comment by warmshao** [comment]
> Does ChatTTSPlus support training my own voice?

yes，sure

**Comment by johnny8353** [comment]
Is there any relevant documentation? Thank you

**Comment by warmshao** [comment]
> Is there any relevant documentation? Thank you

https://github.com/warmshao/ChatTTSPlus/blob/master/assets/docs/voice_clone.md

**Comment by johnny8353** [comment]
> > Is there any relevant documentation? Thank you
> 
> https://github.com/warmshao/ChatTTSPlus/blob/master/assets/docs/voice_clone.md

thank .

when i training my own voice base on this doc.it raise error ：Can you help me see why

`
[20241217 15:25:04] [INFO] DVAE | dvae | loading DVAE pretrained model: /home/zdd/data/workspace/hfq/ChatTTSPlus/chattts_plus/checkpoints/asset/DVAE_full.pt
[20241217 15:25:04] [INFO] Lora Training | train_lora | loading GPT model >>>
[20241217 15:25:06] [INFO] GPT | gpt | loading GPT pretrained model: /home/zdd/data/workspace/hfq/ChatTTSPlus/chattts_plus/checkpoints/asset/GPT.pt
[20241217 15:25:06] [INFO] Lora Training | train_lora | loading speaker stat: /home/zdd/data/workspace/hfq/ChatTTSPlus/chattts_plus/checkpoints/asset/spk_stat.pt
[20241217 15:25:06] [INFO] Lora Training | train_lora | loading normalizer: /home/zdd/data/workspace/hfq/ChatTTSPlus/chattts_plus/checkpoints/homophones_map.json
[20241217 15:25:06] [INFO] Lora Training | train_lora | Setting Lora model >>>
[20241217 15:25:06] [INFO] Lora Training | train_lora | Total trainable params 280
[20241217 15:25:06] [INFO] Lora Training | train_lora | ***** Running training *****
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Num examples = 407
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Num Epochs = 10
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Instantaneous batch size per device = 1
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Total train batch size (w. parallel, distributed & accumulation) = 1
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Gradient Accumulation steps = 1
[20241217 15:25:06] [INFO] Lora Training | train_lora |   Total optimization steps = 4000
Steps:   0%|                                                                                 | 0/4000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zdd/data/workspace/hfq/ChatTTSPlus/train_lora.py", line 542, in <module>
    main(config)
  File "/home/zdd/data/workspace/hfq/ChatTTSPlus/train_lora.py", line 486, in main
    optimizer.step()
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/accelerate/optimizer.py", line 165, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 451, in step
    self.unscale_(optimizer)
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 338, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 260, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
Steps:   0%|                                                                                 | 0/4000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/zdd/anaconda3/envs/chattts_plus/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/zdd/anaconda3/envs/chattts_plus/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zdd/anaconda3/envs/chattts_plus/bin/python', 'train_lora.py', '--config', 'configs/train/train_voice_clone_lora.yaml']' returned non-zero exit status 1.
`


`MODELS:
  tokenizer:
    name: "Tokenizer"
    infer_type: "pytorch"
    kwargs:
      model_path: "checkpoints/asset/tokenizer.pt"
  dvae_encode:
    name: "DVAE"
    infer_type: "pytorch"
    kwargs:
      model_path: "checkpoints/asset/DVAE_full.pt"
      coef: ''
      dim: 512
      decoder_config:
        idim: 512
        odim: 512
        hidden: 256
        n_layer: 12
        bn_dim: 128
      encoder_config:
        idim: 512
        odim: 1024
        hidden: 256
        n_layer: 12
        bn_dim: 128
      vq_config:
        dim: 1024
        levels:
          - 5
          - 5
          - 5
          - 5
        G: 2
        R: 2
  dvae_decode:
    name: "DVAE"
    infer_type: "pytorch"
    kwargs:
      model_path: "checkpoints/asset/Decoder.pt"
      coef: ''
      dim: 384
      decoder_config:
        idim: 384
        odim: 384
        hidden: 512
        n_layer: 12
        bn_dim: 128
  gpt:
    name: "GPT"
    infer_type: "pytorch"
    kwargs:
      model_path: "checkpoints/asset/GPT.pt"
      gpt_config:
        hidden_size: 768
        intermediate_size: 3072
        num_attention_heads: 12
        num_hidden_layers: 20
        use_cache: False
        max_position_embeddings: 4096
        spk_emb_dim: 192
        spk_KL: False
        num_audio_tokens: 626
        num_vq: 4

DATA:
  train_bs: 1
  meta_infos:
    - "/home/zdd/data/workspace/hfq/wenyanping/slicer.list"
  sample_rate: 24000
  num_vq: 4

LORA:
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.01
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  gradient_checkpointing: false
  max_train_steps: 4000
  max_grad_norm: 1.0
  # lr
  learning_rate: 5e-5
  min_learning_rate: 1e-5
  scale_lr: false
  lr_warmup_steps: 10
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: false
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_weight_decay: 1e-3

weight_dtype: 'fp16'
output_dir: './outputs'
exp_name: "wyp2_lora"
lora_model_path: ""
checkpointing_steps: 100
use_empty_speaker: true`
